# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
# Required Notice: Copyright 2026 IoT-AI.Tech / Dr.-Ing. Babak Sorkhpour
# Author: Dr.-Ing. Babak Sorkhpour, with AI assistance
# Version: 1.0.0 | Date: 2026-09-06
"""Read-only installed package source/data consistency, not remote attestation."""
from __future__ import annotations

import base64
import csv
import hashlib
import io
import os
import re
import zipfile
from email.parser import Parser
from pathlib import Path
from typing import Any

from .util import open_secure

MAX_FILE = 16 * 1024 * 1024
MAX_RECORD = 2 * 1024 * 1024
MAX_MEMBERS = 10000
SHA = re.compile(r"[0-9a-f]{64}\Z")


def _name(value: str) -> bool:
    return (bool(value) and not value.startswith("/") and "\\" not in value
            and ":" not in value and "\0" not in value
            and all(part not in {"", ".", ".."} for part in value.split("/")))


def _read(path: Path, root: Path, limit: int = MAX_FILE) -> bytes:
    with open_secure(path, allowed_roots=[root], max_bytes=limit) as stream:
        data = stream.read(limit + 1)
    if len(data) > limit:
        raise ValueError("runtime-member-too-large")
    return data


def _inventory(root: Path) -> tuple[dict[str, Path], int]:
    files: dict[str, Path] = {}
    caches = 0
    for directory, dirs, names in os.walk(root, followlinks=False):
        for name in dirs:
            if (Path(directory) / name).is_symlink():
                raise ValueError("runtime-directory-link")
        for name in names:
            path = Path(directory) / name
            relative = path.relative_to(root).as_posix()
            if path.is_symlink() or not path.is_file():
                raise ValueError("runtime-nonregular-member")
            if "__pycache__" in path.relative_to(root).parts and path.suffix == ".pyc":
                caches += 1
                continue
            files["iot_ai/" + relative] = path
            if len(files) + caches > MAX_MEMBERS:
                raise ValueError("runtime-inventory-too-large")
    return files, caches


def verify_distribution(package_root: Path, *, expected_version: str | None = None,
                        wheel: Path | None = None, wheel_sha256: str | None = None) -> dict[str, Any]:
    """Check exact package source/data membership and hashes against RECORD.

    A retained, digest-bound wheel strengthens this to a second byte inventory.
    Mutable local RECORD/manifest files are consistency anchors, not signatures.
    Python/interpreter dependencies and generated bytecode are expressly outside
    this source/data check; they must not become an executable-authenticity claim.
    """
    result: dict[str, Any] = {"decision": "block", "scope": "installed-package-source-and-data",
        "anchor": "wheel-and-record" if wheel is not None else "record-consistency",
        "checked": 0, "blockers": [], "generated_bytecode_files": 0,
        "execution_authenticity": False, "remote_attestation": False}
    errors = result["blockers"]
    try:
        package_root = Path(package_root)
        if package_root.name != "iot_ai" or package_root.is_symlink() or not package_root.is_dir():
            raise ValueError("runtime-package-root-invalid")
        base = package_root.parent
        metadata = list(base.glob("iot_ai_coder_suite-*.dist-info"))
        if len(metadata) != 1 or metadata[0].is_symlink() or not metadata[0].is_dir():
            raise ValueError("runtime-distribution-metadata-missing-or-ambiguous")
        meta = Parser().parsestr(_read(metadata[0] / "METADATA", base, MAX_RECORD).decode("utf-8"))
        if meta.get("Name", "").lower().replace("_", "-") != "iot-ai-coder-suite":
            raise ValueError("runtime-distribution-name-mismatch")
        result["distribution_version"] = meta.get("Version")
        if expected_version and meta.get("Version") != expected_version:
            raise ValueError("runtime-distribution-version-mismatch")
        record_data = _read(metadata[0] / "RECORD", base, MAX_RECORD)
        result["record_sha256"] = hashlib.sha256(record_data).hexdigest()
        records: dict[str, tuple[str, int]] = {}
        seen: set[str] = set()
        for index, row in enumerate(csv.reader(io.StringIO(record_data.decode("utf-8")))):
            if index >= MAX_MEMBERS or len(row) != 3:
                raise ValueError("runtime-record-invalid")
            name, digest, size = row
            # pip records console scripts outside site-packages. Their wrappers
            # are covered by the host-adapter inventory, never opened from here.
            if not name.startswith("iot_ai/"):
                continue
            if not _name(name) or name.casefold() in seen:
                raise ValueError("runtime-record-path-invalid-or-duplicate")
            seen.add(name.casefold())
            if "__pycache__" in name.split("/") and name.endswith(".pyc"):
                continue
            if not digest.startswith("sha256=") or not re.fullmatch(r"[0-9]{1,9}", size):
                raise ValueError("runtime-record-hash-or-size-invalid")
            encoded = digest.split("=", 1)[1]
            decoded = base64.b64decode(encoded + "=" * (-len(encoded) % 4), altchars=b"-_", validate=True)
            if len(decoded) != 32 or int(size) > MAX_FILE:
                raise ValueError("runtime-record-hash-or-size-invalid")
            records[name] = (decoded.hex(), int(size))
        if not records:
            raise ValueError("runtime-record-empty")
        actual, caches = _inventory(package_root)
        result["generated_bytecode_files"] = caches
        for name in sorted(set(records) - set(actual)):
            errors.append("runtime-missing:" + name)
        for name in sorted(set(actual) - set(records)):
            errors.append("runtime-unlisted:" + name)
        for name in sorted(set(actual) & set(records)):
            data = _read(actual[name], base)
            expected_hash, expected_size = records[name]
            if len(data) != expected_size or hashlib.sha256(data).hexdigest() != expected_hash:
                errors.append("runtime-drift:" + name)
            result["checked"] += 1
        if wheel is not None:
            if not isinstance(wheel_sha256, str) or not SHA.fullmatch(wheel_sha256):
                raise ValueError("runtime-wheel-digest-required")
            wheel = Path(wheel)
            wheel_data = _read(wheel, wheel.parent)
            if hashlib.sha256(wheel_data).hexdigest() != wheel_sha256:
                raise ValueError("runtime-wheel-digest-mismatch")
            wheel_records: dict[str, tuple[str, int]] = {}
            total = 0
            with zipfile.ZipFile(io.BytesIO(wheel_data)) as archive:
                infos = archive.infolist()
                if len(infos) > MAX_MEMBERS or len({i.filename for i in infos}) != len(infos):
                    raise ValueError("runtime-wheel-members-invalid")
                for item in infos:
                    if not item.filename.startswith("iot_ai/") or item.is_dir():
                        continue
                    if not _name(item.filename) or item.file_size > MAX_FILE:
                        raise ValueError("runtime-wheel-member-invalid")
                    total += item.file_size
                    if total > 64 * 1024 * 1024:
                        raise ValueError("runtime-wheel-expanded-limit")
                    data = archive.read(item)
                    wheel_records[item.filename] = (hashlib.sha256(data).hexdigest(), len(data))
            if wheel_records != records:
                errors.append("runtime-wheel-record-mismatch")
        # These roots have priority over wheel-contained skills in legacy loaders.
        for shadow in (base / "skills", base.parent / "skills"):
            if shadow.exists() and (package_root / "data" / "skills").is_dir():
                errors.append("runtime-packaged-skill-shadow")
    except (OSError, ValueError, TypeError, UnicodeError, csv.Error, zipfile.BadZipFile) as exc:
        reason = str(exc) if isinstance(exc, ValueError) and str(exc).startswith("runtime-") else type(exc).__name__
        errors.append("runtime-inspection-failed:" + reason)
    result["decision"] = "pass" if not errors else "block"
    return result
