# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
# Required Notice: Copyright 2026 IoT-AI.Tech / Dr.-Ing. Babak Sorkhpour
# Author: Dr.-Ing. Babak Sorkhpour, with AI assistance
# Version: 6.7.0-beta.4 | Date: 2026-08-08
"""Platform- and database-independent storage ports.

The Community implementation uses SQLite plus versioned files. Enterprise
adapters may implement these ports with PostgreSQL, object storage, or PMD APIs
without changing orchestration contracts.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Iterable, Protocol, runtime_checkable


@runtime_checkable
class StateStore(Protocol):
    def append_event(self, event_type: str, payload: dict[str, Any], *, correlation_id: str) -> str: ...
    def put_graph(self, graph: dict[str, Any]) -> None: ...
    def put_node_result(self, graph_id: str, node_id: str, result: dict[str, Any]) -> None: ...
    def latest_workflow_records(self, limit: int = 100) -> list[dict[str, Any]]: ...


@runtime_checkable
class KnowledgeStore(Protocol):
    def write(self, artifact: dict[str, Any], content: str) -> dict[str, Any]: ...
    def list(self, *, visibility: str, limit: int = 1000) -> list[dict[str, Any]]: ...
    def get(self, artifact_id: str) -> dict[str, Any] | None: ...


@runtime_checkable
class EvidenceStore(Protocol):
    def put(self, source: Path, metadata: dict[str, Any]) -> dict[str, Any]: ...
    def verify(self, evidence_id: str) -> dict[str, Any]: ...


@runtime_checkable
class ProjectionStore(Protocol):
    def project(self, entities: Iterable[dict[str, Any]], output: Path) -> dict[str, Any]: ...



@runtime_checkable
class AgentRuntimeStore(Protocol):
    """Platform-neutral persistence for owned agent-runtime artifacts."""

    def put_goal_contract(self, contract: dict[str, Any]) -> None: ...
    def put_prompt_artifact(self, node_id: str, artifact: dict[str, Any]) -> None: ...
    def put_context_manifest(self, node_id: str, manifest: dict[str, Any]) -> None: ...
    def put_turn_receipt(self, node_id: str, receipt: dict[str, Any]) -> None: ...
    def put_checkpoint(self, checkpoint: dict[str, Any]) -> None: ...
    def latest_runtime_status(self) -> dict[str, Any]: ...

@runtime_checkable
class TaskControlPort(Protocol):
    """Optional task-control boundary used by standalone and PMD adapters."""

    def create_task(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def create_work_unit(self, task_id: str, contract: dict[str, Any]) -> dict[str, Any]: ...
    def claim(self, work_unit_id: str, actor: str, session_id: str) -> dict[str, Any]: ...
    def progress(self, lease_id: str, event: dict[str, Any]) -> dict[str, Any]: ...
    def attach_evidence(self, task_id: str, artifact: dict[str, Any]) -> dict[str, Any]: ...
    def submit(self, task_id: str, receipt: dict[str, Any]) -> dict[str, Any]: ...
